"""Small grayscale PNG reader using only Python's standard library."""

from __future__ import annotations

import struct
import zlib
from pathlib import Path

from common.png_writer import PNG_SIGNATURE


def read_grayscale_png(path: str | Path) -> list[list[int]]:
    """Read an 8-bit grayscale PNG image.

    This supports the PNG files generated by common.png_writer and also handles
    the standard PNG row filters for 8-bit grayscale images.
    """
    data = Path(path).read_bytes()
    if not data.startswith(PNG_SIGNATURE):
        raise ValueError("Not a PNG file")

    width: int | None = None
    height: int | None = None
    bit_depth: int | None = None
    color_type: int | None = None
    compressed_parts: list[bytes] = []

    offset = len(PNG_SIGNATURE)
    while offset < len(data):
        if offset + 8 > len(data):
            raise ValueError("Invalid PNG chunk header")
        chunk_length = struct.unpack(">I", data[offset : offset + 4])[0]
        chunk_type = data[offset + 4 : offset + 8]
        chunk_data_start = offset + 8
        chunk_data_end = chunk_data_start + chunk_length
        chunk_data = data[chunk_data_start:chunk_data_end]
        offset = chunk_data_end + 4

        if chunk_type == b"IHDR":
            width, height, bit_depth, color_type, _, _, _ = struct.unpack(">IIBBBBB", chunk_data)
        elif chunk_type == b"IDAT":
            compressed_parts.append(chunk_data)
        elif chunk_type == b"IEND":
            break

    if width is None or height is None or bit_depth is None or color_type is None:
        raise ValueError("PNG missing IHDR chunk")
    if bit_depth != 8 or color_type != 0:
        raise ValueError("Only 8-bit grayscale PNG images are supported")

    raw = zlib.decompress(b"".join(compressed_parts))
    return _unfilter_grayscale_rows(raw, width, height)


def _unfilter_grayscale_rows(raw: bytes, width: int, height: int) -> list[list[int]]:
    row_size = width + 1
    expected_size = row_size * height
    if len(raw) != expected_size:
        raise ValueError("Unexpected PNG decompressed data size")

    rows: list[list[int]] = []
    previous = [0] * width

    for row_index in range(height):
        row_start = row_index * row_size
        filter_type = raw[row_start]
        encoded = list(raw[row_start + 1 : row_start + row_size])
        decoded = _unfilter_row(filter_type, encoded, previous)
        rows.append(decoded)
        previous = decoded

    return rows


def _unfilter_row(filter_type: int, encoded: list[int], previous: list[int]) -> list[int]:
    decoded: list[int] = []
    for index, value in enumerate(encoded):
        left = decoded[index - 1] if index > 0 else 0
        up = previous[index]
        up_left = previous[index - 1] if index > 0 else 0

        if filter_type == 0:
            decoded_value = value
        elif filter_type == 1:
            decoded_value = value + left
        elif filter_type == 2:
            decoded_value = value + up
        elif filter_type == 3:
            decoded_value = value + ((left + up) // 2)
        elif filter_type == 4:
            decoded_value = value + _paeth_predictor(left, up, up_left)
        else:
            raise ValueError(f"Unsupported PNG filter type: {filter_type}")

        decoded.append(decoded_value & 0xFF)

    return decoded


def _paeth_predictor(left: int, up: int, up_left: int) -> int:
    prediction = left + up - up_left
    distance_left = abs(prediction - left)
    distance_up = abs(prediction - up)
    distance_up_left = abs(prediction - up_left)

    if distance_left <= distance_up and distance_left <= distance_up_left:
        return left
    if distance_up <= distance_up_left:
        return up
    return up_left

